quarkus.application.name=quarkus
quarkus.http.port=8082
quarkus.http.host=0.0.0.0

# Kafka brokers
kafka.bootstrap.servers=kafka1:9092,kafka2:9092

# Canal de salida
mp.messaging.outgoing.whatsapp-out.connector=smallrye-kafka
mp.messaging.outgoing.whatsapp-out.topic=events-whatsapp
mp.messaging.outgoing.whatsapp-out.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.whatsapp-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

# Opcional
mp.messaging.outgoing.whatsapp-out.acks=all