quarkus.application.name=quarkus
quarkus.http.port=8082
quarkus.http.host=0.0.0.0

# Kafka
kafka.bootstrap.servers=kafka1:9092,kafka2:9092

# Producer
mp.messaging.outgoing.whatsapp-out.connector=smallrye-kafka
mp.messaging.outgoing.whatsapp-out.topic=events-whatsapp

# Tanto la key como el value serán String
mp.messaging.outgoing.whatsapp-out.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.whatsapp-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

# Esperar confirmación de todas las réplicas
mp.messaging.outgoing.whatsapp-out.acks=all