####
# This Dockerfile is used in order to build a container that runs the Quarkus application in native (no JVM) mode.
#
# Before building the container image run:
#
# ./mvnw package -Dnative
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.native -t quarkus/poc-quarkus .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 quarkus/poc-quarkus
#
# The ` registry.access.redhat.com/ubi9/ubi-minimal:9.7` base image is based on UBI 9.
# To use UBI 8, switch to `quay.io/ubi8/ubi-minimal:8.10`.
###
FROM registry.access.redhat.com/ubi9/ubi-minimal:9.7
WORKDIR /work/
COPY target/*-runner /work/application
RUN chmod 775 /work/application

EXPOSE 8082

ENTRYPOINT ["./application","-Dquarkus.http.host=0.0.0.0"]