name: Deploy App

on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Give execute permission to mvnw
        run: chmod +x mvnw

      - name: Build Native Executable
        run: |
          ./mvnw package \
          -Dnative \
          -Dquarkus.native.container-build=true \
          -DskipTests

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "."
          target: "/opt/apps/mi-app-quarkus"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}

          script: |
            cd /opt/apps/mi-app-quarkus
            docker-compose down
            docker-compose up -d --build